version: "3"
services:
  native:
    command: cabal run
    build: 
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/monopoly/src

  ghcjs:
    build: 
        context: .
        dockerfile: Dockerfile-ghcjs
    volumes:
      - ./src:/usr/src/monopoly/src
